import os

DATABASE_URL = os.getenv("DATABASE_URL")

STRAVA_WEB_USER = os.getenv("STRAVA_WEB_USER")
STRAVA_WEB_PWD = os.getenv("STRAVA_WEB_PWD")
STRAVA_API_CLIENTID = os.getenv("STRAVA_API_CLIENTIT")
STRAVA_API_CLIENTSECRET = os.getenv("STRAVA_API_CLIENTSECRET")

CLUB_IDS = [445835]
YEAR = 2020